@echo off
set MAC_TO_CONNECT_NUS=F07FEB6BAE30

echo MAC:%MAC_TO_CONNECT_NUS% 
set MAC_VAL1_SRC=:10CB20005828256429000000E8470020A1A2A3A4FA
set MAC_VAL1_DATA=:10CB20005828256429000000E8470020%MAC_TO_CONNECT_NUS:~10,2%%MAC_TO_CONNECT_NUS:~8,2%%MAC_TO_CONNECT_NUS:~6,2%%MAC_TO_CONNECT_NUS:~4,2%
set MAC_VAL1_DST=
set MAC_VAL2_SRC=:10CB3000A5A601000200424C4520554152542063F5
set MAC_VAL2_DATA=:10CB3000%MAC_TO_CONNECT_NUS:~2,2%%MAC_TO_CONNECT_NUS:~0,2%01000200424C4520554152542063
set MAC_VAL1_DST=

echo READ MAC_VAL1_DATA for Calculate Intel Hex Checksum
set /a CHECKSUM_TEMP=0x%MAC_VAL1_DATA:~1,2% + 0x%MAC_VAL1_DATA:~3,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~5,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~7,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~9,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~11,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~13,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~15,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~17,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~19,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~21,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~23,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~25,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~27,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~29,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~31,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~33,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~35,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~37,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL1_DATA:~39,2%
set /a CHECKSUM_TEMP_LSB=%CHECKSUM_TEMP% %% 256

echo Convert %CHECKSUM_TEMP_LSB% to 2's Complement
if %CHECKSUM_TEMP_LSB% == 0 set CHECKSUM_INTELHEX=00
if %CHECKSUM_TEMP_LSB% == 1 set CHECKSUM_INTELHEX=FF
if %CHECKSUM_TEMP_LSB% == 2 set CHECKSUM_INTELHEX=FE
if %CHECKSUM_TEMP_LSB% == 3 set CHECKSUM_INTELHEX=FD
if %CHECKSUM_TEMP_LSB% == 4 set CHECKSUM_INTELHEX=FC
if %CHECKSUM_TEMP_LSB% == 5 set CHECKSUM_INTELHEX=FB
if %CHECKSUM_TEMP_LSB% == 6 set CHECKSUM_INTELHEX=FA
if %CHECKSUM_TEMP_LSB% == 7 set CHECKSUM_INTELHEX=F9
if %CHECKSUM_TEMP_LSB% == 8 set CHECKSUM_INTELHEX=F8
if %CHECKSUM_TEMP_LSB% == 9 set CHECKSUM_INTELHEX=F7
if %CHECKSUM_TEMP_LSB% == 10 set CHECKSUM_INTELHEX=F6
if %CHECKSUM_TEMP_LSB% == 11 set CHECKSUM_INTELHEX=F5
if %CHECKSUM_TEMP_LSB% == 12 set CHECKSUM_INTELHEX=F4
if %CHECKSUM_TEMP_LSB% == 13 set CHECKSUM_INTELHEX=F3
if %CHECKSUM_TEMP_LSB% == 14 set CHECKSUM_INTELHEX=F2
if %CHECKSUM_TEMP_LSB% == 15 set CHECKSUM_INTELHEX=F1
if %CHECKSUM_TEMP_LSB% == 16 set CHECKSUM_INTELHEX=F0
if %CHECKSUM_TEMP_LSB% == 17 set CHECKSUM_INTELHEX=EF
if %CHECKSUM_TEMP_LSB% == 18 set CHECKSUM_INTELHEX=EE
if %CHECKSUM_TEMP_LSB% == 19 set CHECKSUM_INTELHEX=ED
if %CHECKSUM_TEMP_LSB% == 20 set CHECKSUM_INTELHEX=EC
if %CHECKSUM_TEMP_LSB% == 21 set CHECKSUM_INTELHEX=EB
if %CHECKSUM_TEMP_LSB% == 22 set CHECKSUM_INTELHEX=EA
if %CHECKSUM_TEMP_LSB% == 23 set CHECKSUM_INTELHEX=E9
if %CHECKSUM_TEMP_LSB% == 24 set CHECKSUM_INTELHEX=E8
if %CHECKSUM_TEMP_LSB% == 25 set CHECKSUM_INTELHEX=E7
if %CHECKSUM_TEMP_LSB% == 26 set CHECKSUM_INTELHEX=E6
if %CHECKSUM_TEMP_LSB% == 27 set CHECKSUM_INTELHEX=E5
if %CHECKSUM_TEMP_LSB% == 28 set CHECKSUM_INTELHEX=E4
if %CHECKSUM_TEMP_LSB% == 29 set CHECKSUM_INTELHEX=E3
if %CHECKSUM_TEMP_LSB% == 30 set CHECKSUM_INTELHEX=E2
if %CHECKSUM_TEMP_LSB% == 31 set CHECKSUM_INTELHEX=E1
if %CHECKSUM_TEMP_LSB% == 32 set CHECKSUM_INTELHEX=E0
if %CHECKSUM_TEMP_LSB% == 33 set CHECKSUM_INTELHEX=DF
if %CHECKSUM_TEMP_LSB% == 34 set CHECKSUM_INTELHEX=DE
if %CHECKSUM_TEMP_LSB% == 35 set CHECKSUM_INTELHEX=DD
if %CHECKSUM_TEMP_LSB% == 36 set CHECKSUM_INTELHEX=DC
if %CHECKSUM_TEMP_LSB% == 37 set CHECKSUM_INTELHEX=DB
if %CHECKSUM_TEMP_LSB% == 38 set CHECKSUM_INTELHEX=DA
if %CHECKSUM_TEMP_LSB% == 39 set CHECKSUM_INTELHEX=D9
if %CHECKSUM_TEMP_LSB% == 40 set CHECKSUM_INTELHEX=D8
if %CHECKSUM_TEMP_LSB% == 41 set CHECKSUM_INTELHEX=D7
if %CHECKSUM_TEMP_LSB% == 42 set CHECKSUM_INTELHEX=D6
if %CHECKSUM_TEMP_LSB% == 43 set CHECKSUM_INTELHEX=D5
if %CHECKSUM_TEMP_LSB% == 44 set CHECKSUM_INTELHEX=D4
if %CHECKSUM_TEMP_LSB% == 45 set CHECKSUM_INTELHEX=D3
if %CHECKSUM_TEMP_LSB% == 46 set CHECKSUM_INTELHEX=D2
if %CHECKSUM_TEMP_LSB% == 47 set CHECKSUM_INTELHEX=D1
if %CHECKSUM_TEMP_LSB% == 48 set CHECKSUM_INTELHEX=D0
if %CHECKSUM_TEMP_LSB% == 49 set CHECKSUM_INTELHEX=CF
if %CHECKSUM_TEMP_LSB% == 50 set CHECKSUM_INTELHEX=CE
if %CHECKSUM_TEMP_LSB% == 51 set CHECKSUM_INTELHEX=CD
if %CHECKSUM_TEMP_LSB% == 52 set CHECKSUM_INTELHEX=CC
if %CHECKSUM_TEMP_LSB% == 53 set CHECKSUM_INTELHEX=CB
if %CHECKSUM_TEMP_LSB% == 54 set CHECKSUM_INTELHEX=CA
if %CHECKSUM_TEMP_LSB% == 55 set CHECKSUM_INTELHEX=C9
if %CHECKSUM_TEMP_LSB% == 56 set CHECKSUM_INTELHEX=C8
if %CHECKSUM_TEMP_LSB% == 57 set CHECKSUM_INTELHEX=C7
if %CHECKSUM_TEMP_LSB% == 58 set CHECKSUM_INTELHEX=C6
if %CHECKSUM_TEMP_LSB% == 59 set CHECKSUM_INTELHEX=C5
if %CHECKSUM_TEMP_LSB% == 60 set CHECKSUM_INTELHEX=C4
if %CHECKSUM_TEMP_LSB% == 61 set CHECKSUM_INTELHEX=C3
if %CHECKSUM_TEMP_LSB% == 62 set CHECKSUM_INTELHEX=C2
if %CHECKSUM_TEMP_LSB% == 63 set CHECKSUM_INTELHEX=C1
if %CHECKSUM_TEMP_LSB% == 64 set CHECKSUM_INTELHEX=C0
if %CHECKSUM_TEMP_LSB% == 65 set CHECKSUM_INTELHEX=BF
if %CHECKSUM_TEMP_LSB% == 66 set CHECKSUM_INTELHEX=BE
if %CHECKSUM_TEMP_LSB% == 67 set CHECKSUM_INTELHEX=BD
if %CHECKSUM_TEMP_LSB% == 68 set CHECKSUM_INTELHEX=BC
if %CHECKSUM_TEMP_LSB% == 69 set CHECKSUM_INTELHEX=BB
if %CHECKSUM_TEMP_LSB% == 70 set CHECKSUM_INTELHEX=BA
if %CHECKSUM_TEMP_LSB% == 71 set CHECKSUM_INTELHEX=B9
if %CHECKSUM_TEMP_LSB% == 72 set CHECKSUM_INTELHEX=B8
if %CHECKSUM_TEMP_LSB% == 73 set CHECKSUM_INTELHEX=B7
if %CHECKSUM_TEMP_LSB% == 74 set CHECKSUM_INTELHEX=B6
if %CHECKSUM_TEMP_LSB% == 75 set CHECKSUM_INTELHEX=B5
if %CHECKSUM_TEMP_LSB% == 76 set CHECKSUM_INTELHEX=B4
if %CHECKSUM_TEMP_LSB% == 77 set CHECKSUM_INTELHEX=B3
if %CHECKSUM_TEMP_LSB% == 78 set CHECKSUM_INTELHEX=B2
if %CHECKSUM_TEMP_LSB% == 79 set CHECKSUM_INTELHEX=B1
if %CHECKSUM_TEMP_LSB% == 80 set CHECKSUM_INTELHEX=B0
if %CHECKSUM_TEMP_LSB% == 81 set CHECKSUM_INTELHEX=AF
if %CHECKSUM_TEMP_LSB% == 82 set CHECKSUM_INTELHEX=AE
if %CHECKSUM_TEMP_LSB% == 83 set CHECKSUM_INTELHEX=AD
if %CHECKSUM_TEMP_LSB% == 84 set CHECKSUM_INTELHEX=AC
if %CHECKSUM_TEMP_LSB% == 85 set CHECKSUM_INTELHEX=AB
if %CHECKSUM_TEMP_LSB% == 86 set CHECKSUM_INTELHEX=AA
if %CHECKSUM_TEMP_LSB% == 87 set CHECKSUM_INTELHEX=A9
if %CHECKSUM_TEMP_LSB% == 88 set CHECKSUM_INTELHEX=A8
if %CHECKSUM_TEMP_LSB% == 89 set CHECKSUM_INTELHEX=A7
if %CHECKSUM_TEMP_LSB% == 90 set CHECKSUM_INTELHEX=A6
if %CHECKSUM_TEMP_LSB% == 91 set CHECKSUM_INTELHEX=A5
if %CHECKSUM_TEMP_LSB% == 92 set CHECKSUM_INTELHEX=A4
if %CHECKSUM_TEMP_LSB% == 93 set CHECKSUM_INTELHEX=A3
if %CHECKSUM_TEMP_LSB% == 94 set CHECKSUM_INTELHEX=A2
if %CHECKSUM_TEMP_LSB% == 95 set CHECKSUM_INTELHEX=A1
if %CHECKSUM_TEMP_LSB% == 96 set CHECKSUM_INTELHEX=A0
if %CHECKSUM_TEMP_LSB% == 97 set CHECKSUM_INTELHEX=9F
if %CHECKSUM_TEMP_LSB% == 98 set CHECKSUM_INTELHEX=9E
if %CHECKSUM_TEMP_LSB% == 99 set CHECKSUM_INTELHEX=9D
if %CHECKSUM_TEMP_LSB% == 100 set CHECKSUM_INTELHEX=9C
if %CHECKSUM_TEMP_LSB% == 101 set CHECKSUM_INTELHEX=9B
if %CHECKSUM_TEMP_LSB% == 102 set CHECKSUM_INTELHEX=9A
if %CHECKSUM_TEMP_LSB% == 103 set CHECKSUM_INTELHEX=99
if %CHECKSUM_TEMP_LSB% == 104 set CHECKSUM_INTELHEX=98
if %CHECKSUM_TEMP_LSB% == 105 set CHECKSUM_INTELHEX=97
if %CHECKSUM_TEMP_LSB% == 106 set CHECKSUM_INTELHEX=96
if %CHECKSUM_TEMP_LSB% == 107 set CHECKSUM_INTELHEX=95
if %CHECKSUM_TEMP_LSB% == 108 set CHECKSUM_INTELHEX=94
if %CHECKSUM_TEMP_LSB% == 109 set CHECKSUM_INTELHEX=93
if %CHECKSUM_TEMP_LSB% == 110 set CHECKSUM_INTELHEX=92
if %CHECKSUM_TEMP_LSB% == 111 set CHECKSUM_INTELHEX=91
if %CHECKSUM_TEMP_LSB% == 112 set CHECKSUM_INTELHEX=90
if %CHECKSUM_TEMP_LSB% == 113 set CHECKSUM_INTELHEX=8F
if %CHECKSUM_TEMP_LSB% == 114 set CHECKSUM_INTELHEX=8E
if %CHECKSUM_TEMP_LSB% == 115 set CHECKSUM_INTELHEX=8D
if %CHECKSUM_TEMP_LSB% == 116 set CHECKSUM_INTELHEX=8C
if %CHECKSUM_TEMP_LSB% == 117 set CHECKSUM_INTELHEX=8B
if %CHECKSUM_TEMP_LSB% == 118 set CHECKSUM_INTELHEX=8A
if %CHECKSUM_TEMP_LSB% == 119 set CHECKSUM_INTELHEX=89
if %CHECKSUM_TEMP_LSB% == 120 set CHECKSUM_INTELHEX=88
if %CHECKSUM_TEMP_LSB% == 121 set CHECKSUM_INTELHEX=87
if %CHECKSUM_TEMP_LSB% == 122 set CHECKSUM_INTELHEX=86
if %CHECKSUM_TEMP_LSB% == 123 set CHECKSUM_INTELHEX=85
if %CHECKSUM_TEMP_LSB% == 124 set CHECKSUM_INTELHEX=84
if %CHECKSUM_TEMP_LSB% == 125 set CHECKSUM_INTELHEX=83
if %CHECKSUM_TEMP_LSB% == 126 set CHECKSUM_INTELHEX=82
if %CHECKSUM_TEMP_LSB% == 127 set CHECKSUM_INTELHEX=81
if %CHECKSUM_TEMP_LSB% == 128 set CHECKSUM_INTELHEX=80
if %CHECKSUM_TEMP_LSB% == 129 set CHECKSUM_INTELHEX=7F
if %CHECKSUM_TEMP_LSB% == 130 set CHECKSUM_INTELHEX=7E
if %CHECKSUM_TEMP_LSB% == 131 set CHECKSUM_INTELHEX=7D
if %CHECKSUM_TEMP_LSB% == 132 set CHECKSUM_INTELHEX=7C
if %CHECKSUM_TEMP_LSB% == 133 set CHECKSUM_INTELHEX=7B
if %CHECKSUM_TEMP_LSB% == 134 set CHECKSUM_INTELHEX=7A
if %CHECKSUM_TEMP_LSB% == 135 set CHECKSUM_INTELHEX=79
if %CHECKSUM_TEMP_LSB% == 136 set CHECKSUM_INTELHEX=78
if %CHECKSUM_TEMP_LSB% == 137 set CHECKSUM_INTELHEX=77
if %CHECKSUM_TEMP_LSB% == 138 set CHECKSUM_INTELHEX=76
if %CHECKSUM_TEMP_LSB% == 139 set CHECKSUM_INTELHEX=75
if %CHECKSUM_TEMP_LSB% == 140 set CHECKSUM_INTELHEX=74
if %CHECKSUM_TEMP_LSB% == 141 set CHECKSUM_INTELHEX=73
if %CHECKSUM_TEMP_LSB% == 142 set CHECKSUM_INTELHEX=72
if %CHECKSUM_TEMP_LSB% == 143 set CHECKSUM_INTELHEX=71
if %CHECKSUM_TEMP_LSB% == 144 set CHECKSUM_INTELHEX=70
if %CHECKSUM_TEMP_LSB% == 145 set CHECKSUM_INTELHEX=6F
if %CHECKSUM_TEMP_LSB% == 146 set CHECKSUM_INTELHEX=6E
if %CHECKSUM_TEMP_LSB% == 147 set CHECKSUM_INTELHEX=6D
if %CHECKSUM_TEMP_LSB% == 148 set CHECKSUM_INTELHEX=6C
if %CHECKSUM_TEMP_LSB% == 149 set CHECKSUM_INTELHEX=6B
if %CHECKSUM_TEMP_LSB% == 150 set CHECKSUM_INTELHEX=6A
if %CHECKSUM_TEMP_LSB% == 151 set CHECKSUM_INTELHEX=69
if %CHECKSUM_TEMP_LSB% == 152 set CHECKSUM_INTELHEX=68
if %CHECKSUM_TEMP_LSB% == 153 set CHECKSUM_INTELHEX=67
if %CHECKSUM_TEMP_LSB% == 154 set CHECKSUM_INTELHEX=66
if %CHECKSUM_TEMP_LSB% == 155 set CHECKSUM_INTELHEX=65
if %CHECKSUM_TEMP_LSB% == 156 set CHECKSUM_INTELHEX=64
if %CHECKSUM_TEMP_LSB% == 157 set CHECKSUM_INTELHEX=63
if %CHECKSUM_TEMP_LSB% == 158 set CHECKSUM_INTELHEX=62
if %CHECKSUM_TEMP_LSB% == 159 set CHECKSUM_INTELHEX=61
if %CHECKSUM_TEMP_LSB% == 160 set CHECKSUM_INTELHEX=60
if %CHECKSUM_TEMP_LSB% == 161 set CHECKSUM_INTELHEX=5F
if %CHECKSUM_TEMP_LSB% == 162 set CHECKSUM_INTELHEX=5E
if %CHECKSUM_TEMP_LSB% == 163 set CHECKSUM_INTELHEX=5D
if %CHECKSUM_TEMP_LSB% == 164 set CHECKSUM_INTELHEX=5C
if %CHECKSUM_TEMP_LSB% == 165 set CHECKSUM_INTELHEX=5B
if %CHECKSUM_TEMP_LSB% == 166 set CHECKSUM_INTELHEX=5A
if %CHECKSUM_TEMP_LSB% == 167 set CHECKSUM_INTELHEX=59
if %CHECKSUM_TEMP_LSB% == 168 set CHECKSUM_INTELHEX=58
if %CHECKSUM_TEMP_LSB% == 169 set CHECKSUM_INTELHEX=57
if %CHECKSUM_TEMP_LSB% == 170 set CHECKSUM_INTELHEX=56
if %CHECKSUM_TEMP_LSB% == 171 set CHECKSUM_INTELHEX=55
if %CHECKSUM_TEMP_LSB% == 172 set CHECKSUM_INTELHEX=54
if %CHECKSUM_TEMP_LSB% == 173 set CHECKSUM_INTELHEX=53
if %CHECKSUM_TEMP_LSB% == 174 set CHECKSUM_INTELHEX=52
if %CHECKSUM_TEMP_LSB% == 175 set CHECKSUM_INTELHEX=51
if %CHECKSUM_TEMP_LSB% == 176 set CHECKSUM_INTELHEX=50
if %CHECKSUM_TEMP_LSB% == 177 set CHECKSUM_INTELHEX=4F
if %CHECKSUM_TEMP_LSB% == 178 set CHECKSUM_INTELHEX=4E
if %CHECKSUM_TEMP_LSB% == 179 set CHECKSUM_INTELHEX=4D
if %CHECKSUM_TEMP_LSB% == 180 set CHECKSUM_INTELHEX=4C
if %CHECKSUM_TEMP_LSB% == 181 set CHECKSUM_INTELHEX=4B
if %CHECKSUM_TEMP_LSB% == 182 set CHECKSUM_INTELHEX=4A
if %CHECKSUM_TEMP_LSB% == 183 set CHECKSUM_INTELHEX=49
if %CHECKSUM_TEMP_LSB% == 184 set CHECKSUM_INTELHEX=48
if %CHECKSUM_TEMP_LSB% == 185 set CHECKSUM_INTELHEX=47
if %CHECKSUM_TEMP_LSB% == 186 set CHECKSUM_INTELHEX=46
if %CHECKSUM_TEMP_LSB% == 187 set CHECKSUM_INTELHEX=45
if %CHECKSUM_TEMP_LSB% == 188 set CHECKSUM_INTELHEX=44
if %CHECKSUM_TEMP_LSB% == 189 set CHECKSUM_INTELHEX=43
if %CHECKSUM_TEMP_LSB% == 190 set CHECKSUM_INTELHEX=42
if %CHECKSUM_TEMP_LSB% == 191 set CHECKSUM_INTELHEX=41
if %CHECKSUM_TEMP_LSB% == 192 set CHECKSUM_INTELHEX=40
if %CHECKSUM_TEMP_LSB% == 193 set CHECKSUM_INTELHEX=3F
if %CHECKSUM_TEMP_LSB% == 194 set CHECKSUM_INTELHEX=3E
if %CHECKSUM_TEMP_LSB% == 195 set CHECKSUM_INTELHEX=3D
if %CHECKSUM_TEMP_LSB% == 196 set CHECKSUM_INTELHEX=3C
if %CHECKSUM_TEMP_LSB% == 197 set CHECKSUM_INTELHEX=3B
if %CHECKSUM_TEMP_LSB% == 198 set CHECKSUM_INTELHEX=3A
if %CHECKSUM_TEMP_LSB% == 199 set CHECKSUM_INTELHEX=39
if %CHECKSUM_TEMP_LSB% == 200 set CHECKSUM_INTELHEX=38
if %CHECKSUM_TEMP_LSB% == 201 set CHECKSUM_INTELHEX=37
if %CHECKSUM_TEMP_LSB% == 202 set CHECKSUM_INTELHEX=36
if %CHECKSUM_TEMP_LSB% == 203 set CHECKSUM_INTELHEX=35
if %CHECKSUM_TEMP_LSB% == 204 set CHECKSUM_INTELHEX=34
if %CHECKSUM_TEMP_LSB% == 205 set CHECKSUM_INTELHEX=33
if %CHECKSUM_TEMP_LSB% == 206 set CHECKSUM_INTELHEX=32
if %CHECKSUM_TEMP_LSB% == 207 set CHECKSUM_INTELHEX=31
if %CHECKSUM_TEMP_LSB% == 208 set CHECKSUM_INTELHEX=30
if %CHECKSUM_TEMP_LSB% == 209 set CHECKSUM_INTELHEX=2F
if %CHECKSUM_TEMP_LSB% == 210 set CHECKSUM_INTELHEX=2E
if %CHECKSUM_TEMP_LSB% == 211 set CHECKSUM_INTELHEX=2D
if %CHECKSUM_TEMP_LSB% == 212 set CHECKSUM_INTELHEX=2C
if %CHECKSUM_TEMP_LSB% == 213 set CHECKSUM_INTELHEX=2B
if %CHECKSUM_TEMP_LSB% == 214 set CHECKSUM_INTELHEX=2A
if %CHECKSUM_TEMP_LSB% == 215 set CHECKSUM_INTELHEX=29
if %CHECKSUM_TEMP_LSB% == 216 set CHECKSUM_INTELHEX=28
if %CHECKSUM_TEMP_LSB% == 217 set CHECKSUM_INTELHEX=27
if %CHECKSUM_TEMP_LSB% == 218 set CHECKSUM_INTELHEX=26
if %CHECKSUM_TEMP_LSB% == 219 set CHECKSUM_INTELHEX=25
if %CHECKSUM_TEMP_LSB% == 220 set CHECKSUM_INTELHEX=24
if %CHECKSUM_TEMP_LSB% == 221 set CHECKSUM_INTELHEX=23
if %CHECKSUM_TEMP_LSB% == 222 set CHECKSUM_INTELHEX=22
if %CHECKSUM_TEMP_LSB% == 223 set CHECKSUM_INTELHEX=21
if %CHECKSUM_TEMP_LSB% == 224 set CHECKSUM_INTELHEX=20
if %CHECKSUM_TEMP_LSB% == 225 set CHECKSUM_INTELHEX=1F
if %CHECKSUM_TEMP_LSB% == 226 set CHECKSUM_INTELHEX=1E
if %CHECKSUM_TEMP_LSB% == 227 set CHECKSUM_INTELHEX=1D
if %CHECKSUM_TEMP_LSB% == 228 set CHECKSUM_INTELHEX=1C
if %CHECKSUM_TEMP_LSB% == 229 set CHECKSUM_INTELHEX=1B
if %CHECKSUM_TEMP_LSB% == 230 set CHECKSUM_INTELHEX=1A
if %CHECKSUM_TEMP_LSB% == 231 set CHECKSUM_INTELHEX=19
if %CHECKSUM_TEMP_LSB% == 232 set CHECKSUM_INTELHEX=18
if %CHECKSUM_TEMP_LSB% == 233 set CHECKSUM_INTELHEX=17
if %CHECKSUM_TEMP_LSB% == 234 set CHECKSUM_INTELHEX=16
if %CHECKSUM_TEMP_LSB% == 235 set CHECKSUM_INTELHEX=15
if %CHECKSUM_TEMP_LSB% == 236 set CHECKSUM_INTELHEX=14
if %CHECKSUM_TEMP_LSB% == 237 set CHECKSUM_INTELHEX=13
if %CHECKSUM_TEMP_LSB% == 238 set CHECKSUM_INTELHEX=12
if %CHECKSUM_TEMP_LSB% == 239 set CHECKSUM_INTELHEX=11
if %CHECKSUM_TEMP_LSB% == 240 set CHECKSUM_INTELHEX=10
if %CHECKSUM_TEMP_LSB% == 241 set CHECKSUM_INTELHEX=0F
if %CHECKSUM_TEMP_LSB% == 242 set CHECKSUM_INTELHEX=0E
if %CHECKSUM_TEMP_LSB% == 243 set CHECKSUM_INTELHEX=0D
if %CHECKSUM_TEMP_LSB% == 244 set CHECKSUM_INTELHEX=0C
if %CHECKSUM_TEMP_LSB% == 245 set CHECKSUM_INTELHEX=0B
if %CHECKSUM_TEMP_LSB% == 246 set CHECKSUM_INTELHEX=0A
if %CHECKSUM_TEMP_LSB% == 247 set CHECKSUM_INTELHEX=09
if %CHECKSUM_TEMP_LSB% == 248 set CHECKSUM_INTELHEX=08
if %CHECKSUM_TEMP_LSB% == 249 set CHECKSUM_INTELHEX=07
if %CHECKSUM_TEMP_LSB% == 250 set CHECKSUM_INTELHEX=06
if %CHECKSUM_TEMP_LSB% == 251 set CHECKSUM_INTELHEX=05
if %CHECKSUM_TEMP_LSB% == 252 set CHECKSUM_INTELHEX=04
if %CHECKSUM_TEMP_LSB% == 253 set CHECKSUM_INTELHEX=03
if %CHECKSUM_TEMP_LSB% == 254 set CHECKSUM_INTELHEX=02
if %CHECKSUM_TEMP_LSB% == 255 set CHECKSUM_INTELHEX=01
echo CHECKSUM_INTELHEX is %CHECKSUM_INTELHEX%
set MAC_VAL1_DST=%MAC_VAL1_DATA%%CHECKSUM_INTELHEX%
echo MAC_VAL1_DST is %MAC_VAL1_DST%

echo READ MAC_VAL2_DATA for Calculate Intel Hex Checksum
set /a CHECKSUM_TEMP=0x%MAC_VAL2_DATA:~1,2% + 0x%MAC_VAL2_DATA:~3,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~5,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~7,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~9,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~11,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~13,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~15,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~17,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~19,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~21,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~23,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~25,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~27,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~29,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~31,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~33,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~35,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~37,2%
set /a CHECKSUM_TEMP=%CHECKSUM_TEMP% + 0x%MAC_VAL2_DATA:~39,2%
set /a CHECKSUM_TEMP_LSB=%CHECKSUM_TEMP% %% 256

echo Convert %CHECKSUM_TEMP_LSB% to 2's Complement
if %CHECKSUM_TEMP_LSB% == 0 set CHECKSUM_INTELHEX=00
if %CHECKSUM_TEMP_LSB% == 1 set CHECKSUM_INTELHEX=FF
if %CHECKSUM_TEMP_LSB% == 2 set CHECKSUM_INTELHEX=FE
if %CHECKSUM_TEMP_LSB% == 3 set CHECKSUM_INTELHEX=FD
if %CHECKSUM_TEMP_LSB% == 4 set CHECKSUM_INTELHEX=FC
if %CHECKSUM_TEMP_LSB% == 5 set CHECKSUM_INTELHEX=FB
if %CHECKSUM_TEMP_LSB% == 6 set CHECKSUM_INTELHEX=FA
if %CHECKSUM_TEMP_LSB% == 7 set CHECKSUM_INTELHEX=F9
if %CHECKSUM_TEMP_LSB% == 8 set CHECKSUM_INTELHEX=F8
if %CHECKSUM_TEMP_LSB% == 9 set CHECKSUM_INTELHEX=F7
if %CHECKSUM_TEMP_LSB% == 10 set CHECKSUM_INTELHEX=F6
if %CHECKSUM_TEMP_LSB% == 11 set CHECKSUM_INTELHEX=F5
if %CHECKSUM_TEMP_LSB% == 12 set CHECKSUM_INTELHEX=F4
if %CHECKSUM_TEMP_LSB% == 13 set CHECKSUM_INTELHEX=F3
if %CHECKSUM_TEMP_LSB% == 14 set CHECKSUM_INTELHEX=F2
if %CHECKSUM_TEMP_LSB% == 15 set CHECKSUM_INTELHEX=F1
if %CHECKSUM_TEMP_LSB% == 16 set CHECKSUM_INTELHEX=F0
if %CHECKSUM_TEMP_LSB% == 17 set CHECKSUM_INTELHEX=EF
if %CHECKSUM_TEMP_LSB% == 18 set CHECKSUM_INTELHEX=EE
if %CHECKSUM_TEMP_LSB% == 19 set CHECKSUM_INTELHEX=ED
if %CHECKSUM_TEMP_LSB% == 20 set CHECKSUM_INTELHEX=EC
if %CHECKSUM_TEMP_LSB% == 21 set CHECKSUM_INTELHEX=EB
if %CHECKSUM_TEMP_LSB% == 22 set CHECKSUM_INTELHEX=EA
if %CHECKSUM_TEMP_LSB% == 23 set CHECKSUM_INTELHEX=E9
if %CHECKSUM_TEMP_LSB% == 24 set CHECKSUM_INTELHEX=E8
if %CHECKSUM_TEMP_LSB% == 25 set CHECKSUM_INTELHEX=E7
if %CHECKSUM_TEMP_LSB% == 26 set CHECKSUM_INTELHEX=E6
if %CHECKSUM_TEMP_LSB% == 27 set CHECKSUM_INTELHEX=E5
if %CHECKSUM_TEMP_LSB% == 28 set CHECKSUM_INTELHEX=E4
if %CHECKSUM_TEMP_LSB% == 29 set CHECKSUM_INTELHEX=E3
if %CHECKSUM_TEMP_LSB% == 30 set CHECKSUM_INTELHEX=E2
if %CHECKSUM_TEMP_LSB% == 31 set CHECKSUM_INTELHEX=E1
if %CHECKSUM_TEMP_LSB% == 32 set CHECKSUM_INTELHEX=E0
if %CHECKSUM_TEMP_LSB% == 33 set CHECKSUM_INTELHEX=DF
if %CHECKSUM_TEMP_LSB% == 34 set CHECKSUM_INTELHEX=DE
if %CHECKSUM_TEMP_LSB% == 35 set CHECKSUM_INTELHEX=DD
if %CHECKSUM_TEMP_LSB% == 36 set CHECKSUM_INTELHEX=DC
if %CHECKSUM_TEMP_LSB% == 37 set CHECKSUM_INTELHEX=DB
if %CHECKSUM_TEMP_LSB% == 38 set CHECKSUM_INTELHEX=DA
if %CHECKSUM_TEMP_LSB% == 39 set CHECKSUM_INTELHEX=D9
if %CHECKSUM_TEMP_LSB% == 40 set CHECKSUM_INTELHEX=D8
if %CHECKSUM_TEMP_LSB% == 41 set CHECKSUM_INTELHEX=D7
if %CHECKSUM_TEMP_LSB% == 42 set CHECKSUM_INTELHEX=D6
if %CHECKSUM_TEMP_LSB% == 43 set CHECKSUM_INTELHEX=D5
if %CHECKSUM_TEMP_LSB% == 44 set CHECKSUM_INTELHEX=D4
if %CHECKSUM_TEMP_LSB% == 45 set CHECKSUM_INTELHEX=D3
if %CHECKSUM_TEMP_LSB% == 46 set CHECKSUM_INTELHEX=D2
if %CHECKSUM_TEMP_LSB% == 47 set CHECKSUM_INTELHEX=D1
if %CHECKSUM_TEMP_LSB% == 48 set CHECKSUM_INTELHEX=D0
if %CHECKSUM_TEMP_LSB% == 49 set CHECKSUM_INTELHEX=CF
if %CHECKSUM_TEMP_LSB% == 50 set CHECKSUM_INTELHEX=CE
if %CHECKSUM_TEMP_LSB% == 51 set CHECKSUM_INTELHEX=CD
if %CHECKSUM_TEMP_LSB% == 52 set CHECKSUM_INTELHEX=CC
if %CHECKSUM_TEMP_LSB% == 53 set CHECKSUM_INTELHEX=CB
if %CHECKSUM_TEMP_LSB% == 54 set CHECKSUM_INTELHEX=CA
if %CHECKSUM_TEMP_LSB% == 55 set CHECKSUM_INTELHEX=C9
if %CHECKSUM_TEMP_LSB% == 56 set CHECKSUM_INTELHEX=C8
if %CHECKSUM_TEMP_LSB% == 57 set CHECKSUM_INTELHEX=C7
if %CHECKSUM_TEMP_LSB% == 58 set CHECKSUM_INTELHEX=C6
if %CHECKSUM_TEMP_LSB% == 59 set CHECKSUM_INTELHEX=C5
if %CHECKSUM_TEMP_LSB% == 60 set CHECKSUM_INTELHEX=C4
if %CHECKSUM_TEMP_LSB% == 61 set CHECKSUM_INTELHEX=C3
if %CHECKSUM_TEMP_LSB% == 62 set CHECKSUM_INTELHEX=C2
if %CHECKSUM_TEMP_LSB% == 63 set CHECKSUM_INTELHEX=C1
if %CHECKSUM_TEMP_LSB% == 64 set CHECKSUM_INTELHEX=C0
if %CHECKSUM_TEMP_LSB% == 65 set CHECKSUM_INTELHEX=BF
if %CHECKSUM_TEMP_LSB% == 66 set CHECKSUM_INTELHEX=BE
if %CHECKSUM_TEMP_LSB% == 67 set CHECKSUM_INTELHEX=BD
if %CHECKSUM_TEMP_LSB% == 68 set CHECKSUM_INTELHEX=BC
if %CHECKSUM_TEMP_LSB% == 69 set CHECKSUM_INTELHEX=BB
if %CHECKSUM_TEMP_LSB% == 70 set CHECKSUM_INTELHEX=BA
if %CHECKSUM_TEMP_LSB% == 71 set CHECKSUM_INTELHEX=B9
if %CHECKSUM_TEMP_LSB% == 72 set CHECKSUM_INTELHEX=B8
if %CHECKSUM_TEMP_LSB% == 73 set CHECKSUM_INTELHEX=B7
if %CHECKSUM_TEMP_LSB% == 74 set CHECKSUM_INTELHEX=B6
if %CHECKSUM_TEMP_LSB% == 75 set CHECKSUM_INTELHEX=B5
if %CHECKSUM_TEMP_LSB% == 76 set CHECKSUM_INTELHEX=B4
if %CHECKSUM_TEMP_LSB% == 77 set CHECKSUM_INTELHEX=B3
if %CHECKSUM_TEMP_LSB% == 78 set CHECKSUM_INTELHEX=B2
if %CHECKSUM_TEMP_LSB% == 79 set CHECKSUM_INTELHEX=B1
if %CHECKSUM_TEMP_LSB% == 80 set CHECKSUM_INTELHEX=B0
if %CHECKSUM_TEMP_LSB% == 81 set CHECKSUM_INTELHEX=AF
if %CHECKSUM_TEMP_LSB% == 82 set CHECKSUM_INTELHEX=AE
if %CHECKSUM_TEMP_LSB% == 83 set CHECKSUM_INTELHEX=AD
if %CHECKSUM_TEMP_LSB% == 84 set CHECKSUM_INTELHEX=AC
if %CHECKSUM_TEMP_LSB% == 85 set CHECKSUM_INTELHEX=AB
if %CHECKSUM_TEMP_LSB% == 86 set CHECKSUM_INTELHEX=AA
if %CHECKSUM_TEMP_LSB% == 87 set CHECKSUM_INTELHEX=A9
if %CHECKSUM_TEMP_LSB% == 88 set CHECKSUM_INTELHEX=A8
if %CHECKSUM_TEMP_LSB% == 89 set CHECKSUM_INTELHEX=A7
if %CHECKSUM_TEMP_LSB% == 90 set CHECKSUM_INTELHEX=A6
if %CHECKSUM_TEMP_LSB% == 91 set CHECKSUM_INTELHEX=A5
if %CHECKSUM_TEMP_LSB% == 92 set CHECKSUM_INTELHEX=A4
if %CHECKSUM_TEMP_LSB% == 93 set CHECKSUM_INTELHEX=A3
if %CHECKSUM_TEMP_LSB% == 94 set CHECKSUM_INTELHEX=A2
if %CHECKSUM_TEMP_LSB% == 95 set CHECKSUM_INTELHEX=A1
if %CHECKSUM_TEMP_LSB% == 96 set CHECKSUM_INTELHEX=A0
if %CHECKSUM_TEMP_LSB% == 97 set CHECKSUM_INTELHEX=9F
if %CHECKSUM_TEMP_LSB% == 98 set CHECKSUM_INTELHEX=9E
if %CHECKSUM_TEMP_LSB% == 99 set CHECKSUM_INTELHEX=9D
if %CHECKSUM_TEMP_LSB% == 100 set CHECKSUM_INTELHEX=9C
if %CHECKSUM_TEMP_LSB% == 101 set CHECKSUM_INTELHEX=9B
if %CHECKSUM_TEMP_LSB% == 102 set CHECKSUM_INTELHEX=9A
if %CHECKSUM_TEMP_LSB% == 103 set CHECKSUM_INTELHEX=99
if %CHECKSUM_TEMP_LSB% == 104 set CHECKSUM_INTELHEX=98
if %CHECKSUM_TEMP_LSB% == 105 set CHECKSUM_INTELHEX=97
if %CHECKSUM_TEMP_LSB% == 106 set CHECKSUM_INTELHEX=96
if %CHECKSUM_TEMP_LSB% == 107 set CHECKSUM_INTELHEX=95
if %CHECKSUM_TEMP_LSB% == 108 set CHECKSUM_INTELHEX=94
if %CHECKSUM_TEMP_LSB% == 109 set CHECKSUM_INTELHEX=93
if %CHECKSUM_TEMP_LSB% == 110 set CHECKSUM_INTELHEX=92
if %CHECKSUM_TEMP_LSB% == 111 set CHECKSUM_INTELHEX=91
if %CHECKSUM_TEMP_LSB% == 112 set CHECKSUM_INTELHEX=90
if %CHECKSUM_TEMP_LSB% == 113 set CHECKSUM_INTELHEX=8F
if %CHECKSUM_TEMP_LSB% == 114 set CHECKSUM_INTELHEX=8E
if %CHECKSUM_TEMP_LSB% == 115 set CHECKSUM_INTELHEX=8D
if %CHECKSUM_TEMP_LSB% == 116 set CHECKSUM_INTELHEX=8C
if %CHECKSUM_TEMP_LSB% == 117 set CHECKSUM_INTELHEX=8B
if %CHECKSUM_TEMP_LSB% == 118 set CHECKSUM_INTELHEX=8A
if %CHECKSUM_TEMP_LSB% == 119 set CHECKSUM_INTELHEX=89
if %CHECKSUM_TEMP_LSB% == 120 set CHECKSUM_INTELHEX=88
if %CHECKSUM_TEMP_LSB% == 121 set CHECKSUM_INTELHEX=87
if %CHECKSUM_TEMP_LSB% == 122 set CHECKSUM_INTELHEX=86
if %CHECKSUM_TEMP_LSB% == 123 set CHECKSUM_INTELHEX=85
if %CHECKSUM_TEMP_LSB% == 124 set CHECKSUM_INTELHEX=84
if %CHECKSUM_TEMP_LSB% == 125 set CHECKSUM_INTELHEX=83
if %CHECKSUM_TEMP_LSB% == 126 set CHECKSUM_INTELHEX=82
if %CHECKSUM_TEMP_LSB% == 127 set CHECKSUM_INTELHEX=81
if %CHECKSUM_TEMP_LSB% == 128 set CHECKSUM_INTELHEX=80
if %CHECKSUM_TEMP_LSB% == 129 set CHECKSUM_INTELHEX=7F
if %CHECKSUM_TEMP_LSB% == 130 set CHECKSUM_INTELHEX=7E
if %CHECKSUM_TEMP_LSB% == 131 set CHECKSUM_INTELHEX=7D
if %CHECKSUM_TEMP_LSB% == 132 set CHECKSUM_INTELHEX=7C
if %CHECKSUM_TEMP_LSB% == 133 set CHECKSUM_INTELHEX=7B
if %CHECKSUM_TEMP_LSB% == 134 set CHECKSUM_INTELHEX=7A
if %CHECKSUM_TEMP_LSB% == 135 set CHECKSUM_INTELHEX=79
if %CHECKSUM_TEMP_LSB% == 136 set CHECKSUM_INTELHEX=78
if %CHECKSUM_TEMP_LSB% == 137 set CHECKSUM_INTELHEX=77
if %CHECKSUM_TEMP_LSB% == 138 set CHECKSUM_INTELHEX=76
if %CHECKSUM_TEMP_LSB% == 139 set CHECKSUM_INTELHEX=75
if %CHECKSUM_TEMP_LSB% == 140 set CHECKSUM_INTELHEX=74
if %CHECKSUM_TEMP_LSB% == 141 set CHECKSUM_INTELHEX=73
if %CHECKSUM_TEMP_LSB% == 142 set CHECKSUM_INTELHEX=72
if %CHECKSUM_TEMP_LSB% == 143 set CHECKSUM_INTELHEX=71
if %CHECKSUM_TEMP_LSB% == 144 set CHECKSUM_INTELHEX=70
if %CHECKSUM_TEMP_LSB% == 145 set CHECKSUM_INTELHEX=6F
if %CHECKSUM_TEMP_LSB% == 146 set CHECKSUM_INTELHEX=6E
if %CHECKSUM_TEMP_LSB% == 147 set CHECKSUM_INTELHEX=6D
if %CHECKSUM_TEMP_LSB% == 148 set CHECKSUM_INTELHEX=6C
if %CHECKSUM_TEMP_LSB% == 149 set CHECKSUM_INTELHEX=6B
if %CHECKSUM_TEMP_LSB% == 150 set CHECKSUM_INTELHEX=6A
if %CHECKSUM_TEMP_LSB% == 151 set CHECKSUM_INTELHEX=69
if %CHECKSUM_TEMP_LSB% == 152 set CHECKSUM_INTELHEX=68
if %CHECKSUM_TEMP_LSB% == 153 set CHECKSUM_INTELHEX=67
if %CHECKSUM_TEMP_LSB% == 154 set CHECKSUM_INTELHEX=66
if %CHECKSUM_TEMP_LSB% == 155 set CHECKSUM_INTELHEX=65
if %CHECKSUM_TEMP_LSB% == 156 set CHECKSUM_INTELHEX=64
if %CHECKSUM_TEMP_LSB% == 157 set CHECKSUM_INTELHEX=63
if %CHECKSUM_TEMP_LSB% == 158 set CHECKSUM_INTELHEX=62
if %CHECKSUM_TEMP_LSB% == 159 set CHECKSUM_INTELHEX=61
if %CHECKSUM_TEMP_LSB% == 160 set CHECKSUM_INTELHEX=60
if %CHECKSUM_TEMP_LSB% == 161 set CHECKSUM_INTELHEX=5F
if %CHECKSUM_TEMP_LSB% == 162 set CHECKSUM_INTELHEX=5E
if %CHECKSUM_TEMP_LSB% == 163 set CHECKSUM_INTELHEX=5D
if %CHECKSUM_TEMP_LSB% == 164 set CHECKSUM_INTELHEX=5C
if %CHECKSUM_TEMP_LSB% == 165 set CHECKSUM_INTELHEX=5B
if %CHECKSUM_TEMP_LSB% == 166 set CHECKSUM_INTELHEX=5A
if %CHECKSUM_TEMP_LSB% == 167 set CHECKSUM_INTELHEX=59
if %CHECKSUM_TEMP_LSB% == 168 set CHECKSUM_INTELHEX=58
if %CHECKSUM_TEMP_LSB% == 169 set CHECKSUM_INTELHEX=57
if %CHECKSUM_TEMP_LSB% == 170 set CHECKSUM_INTELHEX=56
if %CHECKSUM_TEMP_LSB% == 171 set CHECKSUM_INTELHEX=55
if %CHECKSUM_TEMP_LSB% == 172 set CHECKSUM_INTELHEX=54
if %CHECKSUM_TEMP_LSB% == 173 set CHECKSUM_INTELHEX=53
if %CHECKSUM_TEMP_LSB% == 174 set CHECKSUM_INTELHEX=52
if %CHECKSUM_TEMP_LSB% == 175 set CHECKSUM_INTELHEX=51
if %CHECKSUM_TEMP_LSB% == 176 set CHECKSUM_INTELHEX=50
if %CHECKSUM_TEMP_LSB% == 177 set CHECKSUM_INTELHEX=4F
if %CHECKSUM_TEMP_LSB% == 178 set CHECKSUM_INTELHEX=4E
if %CHECKSUM_TEMP_LSB% == 179 set CHECKSUM_INTELHEX=4D
if %CHECKSUM_TEMP_LSB% == 180 set CHECKSUM_INTELHEX=4C
if %CHECKSUM_TEMP_LSB% == 181 set CHECKSUM_INTELHEX=4B
if %CHECKSUM_TEMP_LSB% == 182 set CHECKSUM_INTELHEX=4A
if %CHECKSUM_TEMP_LSB% == 183 set CHECKSUM_INTELHEX=49
if %CHECKSUM_TEMP_LSB% == 184 set CHECKSUM_INTELHEX=48
if %CHECKSUM_TEMP_LSB% == 185 set CHECKSUM_INTELHEX=47
if %CHECKSUM_TEMP_LSB% == 186 set CHECKSUM_INTELHEX=46
if %CHECKSUM_TEMP_LSB% == 187 set CHECKSUM_INTELHEX=45
if %CHECKSUM_TEMP_LSB% == 188 set CHECKSUM_INTELHEX=44
if %CHECKSUM_TEMP_LSB% == 189 set CHECKSUM_INTELHEX=43
if %CHECKSUM_TEMP_LSB% == 190 set CHECKSUM_INTELHEX=42
if %CHECKSUM_TEMP_LSB% == 191 set CHECKSUM_INTELHEX=41
if %CHECKSUM_TEMP_LSB% == 192 set CHECKSUM_INTELHEX=40
if %CHECKSUM_TEMP_LSB% == 193 set CHECKSUM_INTELHEX=3F
if %CHECKSUM_TEMP_LSB% == 194 set CHECKSUM_INTELHEX=3E
if %CHECKSUM_TEMP_LSB% == 195 set CHECKSUM_INTELHEX=3D
if %CHECKSUM_TEMP_LSB% == 196 set CHECKSUM_INTELHEX=3C
if %CHECKSUM_TEMP_LSB% == 197 set CHECKSUM_INTELHEX=3B
if %CHECKSUM_TEMP_LSB% == 198 set CHECKSUM_INTELHEX=3A
if %CHECKSUM_TEMP_LSB% == 199 set CHECKSUM_INTELHEX=39
if %CHECKSUM_TEMP_LSB% == 200 set CHECKSUM_INTELHEX=38
if %CHECKSUM_TEMP_LSB% == 201 set CHECKSUM_INTELHEX=37
if %CHECKSUM_TEMP_LSB% == 202 set CHECKSUM_INTELHEX=36
if %CHECKSUM_TEMP_LSB% == 203 set CHECKSUM_INTELHEX=35
if %CHECKSUM_TEMP_LSB% == 204 set CHECKSUM_INTELHEX=34
if %CHECKSUM_TEMP_LSB% == 205 set CHECKSUM_INTELHEX=33
if %CHECKSUM_TEMP_LSB% == 206 set CHECKSUM_INTELHEX=32
if %CHECKSUM_TEMP_LSB% == 207 set CHECKSUM_INTELHEX=31
if %CHECKSUM_TEMP_LSB% == 208 set CHECKSUM_INTELHEX=30
if %CHECKSUM_TEMP_LSB% == 209 set CHECKSUM_INTELHEX=2F
if %CHECKSUM_TEMP_LSB% == 210 set CHECKSUM_INTELHEX=2E
if %CHECKSUM_TEMP_LSB% == 211 set CHECKSUM_INTELHEX=2D
if %CHECKSUM_TEMP_LSB% == 212 set CHECKSUM_INTELHEX=2C
if %CHECKSUM_TEMP_LSB% == 213 set CHECKSUM_INTELHEX=2B
if %CHECKSUM_TEMP_LSB% == 214 set CHECKSUM_INTELHEX=2A
if %CHECKSUM_TEMP_LSB% == 215 set CHECKSUM_INTELHEX=29
if %CHECKSUM_TEMP_LSB% == 216 set CHECKSUM_INTELHEX=28
if %CHECKSUM_TEMP_LSB% == 217 set CHECKSUM_INTELHEX=27
if %CHECKSUM_TEMP_LSB% == 218 set CHECKSUM_INTELHEX=26
if %CHECKSUM_TEMP_LSB% == 219 set CHECKSUM_INTELHEX=25
if %CHECKSUM_TEMP_LSB% == 220 set CHECKSUM_INTELHEX=24
if %CHECKSUM_TEMP_LSB% == 221 set CHECKSUM_INTELHEX=23
if %CHECKSUM_TEMP_LSB% == 222 set CHECKSUM_INTELHEX=22
if %CHECKSUM_TEMP_LSB% == 223 set CHECKSUM_INTELHEX=21
if %CHECKSUM_TEMP_LSB% == 224 set CHECKSUM_INTELHEX=20
if %CHECKSUM_TEMP_LSB% == 225 set CHECKSUM_INTELHEX=1F
if %CHECKSUM_TEMP_LSB% == 226 set CHECKSUM_INTELHEX=1E
if %CHECKSUM_TEMP_LSB% == 227 set CHECKSUM_INTELHEX=1D
if %CHECKSUM_TEMP_LSB% == 228 set CHECKSUM_INTELHEX=1C
if %CHECKSUM_TEMP_LSB% == 229 set CHECKSUM_INTELHEX=1B
if %CHECKSUM_TEMP_LSB% == 230 set CHECKSUM_INTELHEX=1A
if %CHECKSUM_TEMP_LSB% == 231 set CHECKSUM_INTELHEX=19
if %CHECKSUM_TEMP_LSB% == 232 set CHECKSUM_INTELHEX=18
if %CHECKSUM_TEMP_LSB% == 233 set CHECKSUM_INTELHEX=17
if %CHECKSUM_TEMP_LSB% == 234 set CHECKSUM_INTELHEX=16
if %CHECKSUM_TEMP_LSB% == 235 set CHECKSUM_INTELHEX=15
if %CHECKSUM_TEMP_LSB% == 236 set CHECKSUM_INTELHEX=14
if %CHECKSUM_TEMP_LSB% == 237 set CHECKSUM_INTELHEX=13
if %CHECKSUM_TEMP_LSB% == 238 set CHECKSUM_INTELHEX=12
if %CHECKSUM_TEMP_LSB% == 239 set CHECKSUM_INTELHEX=11
if %CHECKSUM_TEMP_LSB% == 240 set CHECKSUM_INTELHEX=10
if %CHECKSUM_TEMP_LSB% == 241 set CHECKSUM_INTELHEX=0F
if %CHECKSUM_TEMP_LSB% == 242 set CHECKSUM_INTELHEX=0E
if %CHECKSUM_TEMP_LSB% == 243 set CHECKSUM_INTELHEX=0D
if %CHECKSUM_TEMP_LSB% == 244 set CHECKSUM_INTELHEX=0C
if %CHECKSUM_TEMP_LSB% == 245 set CHECKSUM_INTELHEX=0B
if %CHECKSUM_TEMP_LSB% == 246 set CHECKSUM_INTELHEX=0A
if %CHECKSUM_TEMP_LSB% == 247 set CHECKSUM_INTELHEX=09
if %CHECKSUM_TEMP_LSB% == 248 set CHECKSUM_INTELHEX=08
if %CHECKSUM_TEMP_LSB% == 249 set CHECKSUM_INTELHEX=07
if %CHECKSUM_TEMP_LSB% == 250 set CHECKSUM_INTELHEX=06
if %CHECKSUM_TEMP_LSB% == 251 set CHECKSUM_INTELHEX=05
if %CHECKSUM_TEMP_LSB% == 252 set CHECKSUM_INTELHEX=04
if %CHECKSUM_TEMP_LSB% == 253 set CHECKSUM_INTELHEX=03
if %CHECKSUM_TEMP_LSB% == 254 set CHECKSUM_INTELHEX=02
if %CHECKSUM_TEMP_LSB% == 255 set CHECKSUM_INTELHEX=01
echo CHECKSUM_INTELHEX is %CHECKSUM_INTELHEX%
set MAC_VAL2_DST=%MAC_VAL2_DATA%%CHECKSUM_INTELHEX%
echo MAC_VAL2_DST is %MAC_VAL2_DST%

..\..\usr_bin\mergehex.exe -m ..\softdeviesHex\s132_nrf52_6.1.1_softdevice.hex ble_app_uart_c_pca10040_s132.hex -o ble_app_uart_c_org.hex

if exist ble_app_uart_c.hex (
    DEL /Q ble_app_uart_c.hex
)

echo Generating HEX. Please wait.
for /f "usebackq tokens=* delims=" %%f in (ble_app_uart_c_org.hex) do (
    if %%f == %MAC_VAL1_SRC% echo %MAC_VAL1_DST%>>ble_app_uart_c.hex
    if %%f == %MAC_VAL1_SRC% echo %MAC_VAL2_DST%>>ble_app_uart_c.hex
    if not %%f == %MAC_VAL1_SRC% if not %%f == %MAC_VAL2_SRC% echo %%f>>ble_app_uart_c.hex
)

DEL /Q ble_app_uart_c_org.hex

goto ENDBAT

:ENDBAT
echo Done.

